xname: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Installer Docker
        uses: docker/setup-buildx-action@v2

      - name: VÃ©rifier Docker et Compose
        run: |
          docker --version
          docker compose version

       - name: Lancer les conteneurs
        run: docker compose up --build -d
