name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Installer Docker
        uses: docker/setup-buildx-action@v2

      - name: Installer Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=2.20.2
          sudo curl -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Lancer Docker Compose
        run: sudo docker-compose up --build -d

